### ISSUE TITLE
Это тоже не совсем понятно.

### ISSUE THREAD

**Issue by akluchni** [GoodStartGameDev/VKR#14]
https://github.com/GoodStartGameDev/VKR/blob/1b6e396c292ef6b55a12ea50a03b56df3f945c0f/WinFormsApp1/Processing.cs#LL349C13-L352C59

**Comment by GoodStartGameDev** [comment]
Это указатели для параметров разметочных прямоугольников найденных объектов - они нужны для передачи в функцию Deep_proccessing, в результате которой они должны измениться.
